/**
 * 自动生成今日任务
 *
 * 用于替代 pg_cron 定时任务
 * 在用户每天首次访问时自动检查并生成今日任务
 */

import { triggerDailyTaskGeneration } from '@/services/learning-plan'

const LAST_GENERATION_DATE_KEY = 'last_daily_task_generation_date'

/**
 * 获取上次生成任务的日期
 */
function getLastGenerationDate(): string | null {
  if (typeof window === 'undefined') return null

  try {
    return localStorage.getItem(LAST_GENERATION_DATE_KEY)
  } catch {
    return null
  }
}

/**
 * 获取本地日期字符串（YYYY-MM-DD 格式，使用本地时区）
 */
function getLocalDateString(): string {
  const now = new Date()
  const year = now.getFullYear()
  const month = String(now.getMonth() + 1).padStart(2, '0')
  const day = String(now.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

/**
 * 保存今日已生成任务的标记
 */
function setTodayGenerated(): void {
  if (typeof window === 'undefined') return

  try {
    const today = getLocalDateString()  // ✅ 使用本地时区
    localStorage.setItem(LAST_GENERATION_DATE_KEY, today)
  } catch (error) {
    console.warn('Failed to save generation date:', error)
  }
}

/**
 * 检查今天是否已经生成过任务
 */
function isTodayGenerated(): boolean {
  const lastDate = getLastGenerationDate()
  if (!lastDate) return false

  const today = getLocalDateString()  // ✅ 使用本地时区
  return lastDate === today
}

/**
 * 自动生成今日任务（如果今天还没有生成）
 *
 * 建议在以下场景调用：
 * 1. 首页加载时
 * 2. 用户登录后
 * 3. 学习计划工作台加载时
 *
 * @returns 是否成功生成（true=新生成，false=已存在或失败）
 */
export async function autoGenerateDailyTasksIfNeeded(): Promise<{
  generated: boolean
  alreadyExists: boolean
  error?: string
}> {
  // 如果今天已经生成过，跳过
  if (isTodayGenerated()) {
    return { generated: false, alreadyExists: true }
  }

  try {
    console.log('📅 [AutoDailyTask] 检查今日任务...')

    // 调用 API 生成今日任务
    const result = await triggerDailyTaskGeneration()

    if (result.success) {
      // 标记今天已生成
      setTodayGenerated()

      const { data } = result
      console.log('✅ [AutoDailyTask] 今日任务生成成功:', {
        generated: data?.generated,
        skipped: data?.skipped,
        errors: data?.errors
      })

      return {
        generated: true,
        alreadyExists: false
      }
    } else {
      console.error('❌ [AutoDailyTask] 生成失败:', result.error)
      return {
        generated: false,
        alreadyExists: false,
        error: result.error
      }
    }
  } catch (error: any) {
    console.error('❌ [AutoDailyTask] 异常:', error)
    return {
      generated: false,
      alreadyExists: false,
      error: error.message
    }
  }
}

/**
 * 重除今日生成标记（用于测试）
 */
export function clearTodayGenerationFlag(): void {
  if (typeof window === 'undefined') return

  try {
    localStorage.removeItem(LAST_GENERATION_DATE_KEY)
    console.log('🧹 [AutoDailyTask] 已清除今日生成标记')
  } catch (error) {
    console.warn('Failed to clear flag:', error)
  }
}
