'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { toast } from 'sonner'
import { BookOpen, Plus, Trash2, Sparkles, Calendar, X } from 'lucide-react'
import { getLearningPlans, deleteLearningPlan } from '@/services/learning-plan'
import { DailyTaskDisplay } from './DailyTaskDisplay'
import { LearningPlanSetup } from './LearningPlanSetup'
import type { LearningPlan } from '@/types/learning-plan'
import { useTheme } from '@/contexts/ThemeContext'
import { autoGenerateDailyTasksIfNeeded } from '@/lib/auto-daily-task'

interface BookData {
  id: string
  title: string
  total_words: number
  description?: string
}

export function LearningPlanWorkspace({ books }: { books: BookData[] }) {
  const { theme, mounted } = useTheme()
  const isDark = mounted && theme === 'dark'
  const router = useRouter()

  // 状态管理
  const [plans, setPlans] = useState<LearningPlan[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [isAutoGenerating, setIsAutoGenerating] = useState(false) // 🆕 自动生成状态
  const [selectedPlanIndex, setSelectedPlanIndex] = useState(0)
  const [showCreateDialog, setShowCreateDialog] = useState(false)
  const [selectedBookForPlan, setSelectedBookForPlan] = useState<BookData | null>(null)
  const [showSetupForm, setShowSetupForm] = useState(false)
  const [editingPlan, setEditingPlan] = useState<LearningPlan | null>(null) // 🆕 编辑中的计划
  const [editingBookTitle, setEditingBookTitle] = useState<string>('') // 🆕 编辑中的书名

  // 加载学习计划
  useEffect(() => {
    loadPlans()
  }, [])

  // 🆕 从 localStorage 恢复上次选择的词库
  useEffect(() => {
    if (plans.length === 0) return

    try {
      const savedBookId = localStorage.getItem('learning-plan-last-selected-book')
      if (savedBookId) {
        const savedIndex = plans.findIndex(p => p.book_id === savedBookId)
        if (savedIndex >= 0) {
          console.log('[LearningPlanWorkspace] 恢复上次选择的词库:', savedBookId, '索引:', savedIndex)
          setSelectedPlanIndex(savedIndex)
        }
      }
    } catch (error) {
      console.error('[LearningPlanWorkspace] 读取 localStorage 失败:', error)
    }
  }, [plans])

  // 🆕 保存当前选择的词库到 localStorage
  useEffect(() => {
    if (plans.length === 0) return

    try {
      const selectedPlan = plans[selectedPlanIndex]
      if (selectedPlan) {
        localStorage.setItem('learning-plan-last-selected-book', selectedPlan.book_id)
        console.log('[LearningPlanWorkspace] 保存当前选择的词库:', selectedPlan.book_id)
      }
    } catch (error) {
      console.error('[LearningPlanWorkspace] 保存到 localStorage 失败:', error)
    }
  }, [selectedPlanIndex, plans])

  // ============================================
  // 🔴 自动生成今日任务（前端检查）
  // ============================================
  // ⚠️ 用户要求：暂时注释掉自动检查逻辑，后续待定
  //
  // 原因：
  // 1. Vercel Cron 每天凌晨0点自动生成今日任务（主机制）
  // 2. 前端自动检查会增加页面加载时间
  // 3. 造成不必要的 API 调用
  //
  // 后续方案：
  // - 在 DailyTaskDisplay 组件中添加错误处理
  // - 当今日任务加载失败时，显示"点击刷新"按钮
  // - 让用户手动触发，提升性能
  //
  // ============================================
  /*
  useEffect(() => {
    const autoGenerate = async () => {
      setIsAutoGenerating(true)
      try {
        const result = await autoGenerateDailyTasksIfNeeded()
        if (result.generated) {
          console.log('[Backup] 今日任务已通过前端生成')
          // 重新加载计划数据
          loadPlans()
        }
      } catch (error) {
        // 完全静默，不影响用户体验
      } finally {
        setIsAutoGenerating(false)
      }
    }

    // 延迟执行，优先显示 UI
    const timer = setTimeout(() => {
      autoGenerate()
    }, 100)

    return () => clearTimeout(timer)
  }, [])
  */

  const loadPlans = async () => {
    try {
      const response = await getLearningPlans()
      if (response.success && response.data) {
        setPlans(response.data)
      }
    } catch (error: any) {
      console.error('Failed to load learning plans:', error)
      toast.error('加载学习计划失败')
    } finally {
      setIsLoading(false)
    }
  }

  // 处理创建计划成功
  const handlePlanCreated = async () => {
    setShowSetupForm(false)
    setSelectedBookForPlan(null)
    setShowCreateDialog(false)

    // 重新加载计划列表
    await loadPlans()

    // 选中新创建的计划（最后一个）
    setTimeout(() => {
      setPlans(currentPlans => {
        const newIndex = currentPlans.length - 1
        setSelectedPlanIndex(newIndex >= 0 ? newIndex : 0)
        return currentPlans
      })
    }, 100)

    toast.success('学习计划创建成功！')
  }

  // 打开创建对话框
  const handleOpenCreateDialog = () => {
    if (!canCreateMore) {
      toast.error('最多只能创建3个学习计划，请先删除现有计划')
      return
    }
    setShowCreateDialog(true)
  }

  // 选择书籍进行创建
  const handleSelectBookForPlan = (book: BookData) => {
    setSelectedBookForPlan(book)
    setShowSetupForm(true)
  }

  // 处理删除计划
  const handleDeletePlan = async (planId: string, bookTitle: string) => {
    if (!confirm(`确定要删除「${bookTitle}」的学习计划吗？`)) {
      return
    }

    try {
      const result = await deleteLearningPlan(planId)

      if (result.success) {
        toast.success('学习计划已删除')
        loadPlans()
        // 如果删除的是当前选中的计划，切换到第一个
        if (selectedPlanIndex >= plans.length - 1) {
          setSelectedPlanIndex(Math.max(0, plans.length - 2))
        }
      } else {
        toast.error(result.error || '删除失败')
      }
    } catch (error: any) {
      console.error('Failed to delete plan:', error)
      toast.error('删除学习计划失败')
    }
  }

  // 🆕 处理编辑学习计划
  const handleEditPlan = (plan: LearningPlan, bookTitle: string) => {
    setEditingPlan(plan)
    setEditingBookTitle(bookTitle)
    setShowSetupForm(true)
    setShowCreateDialog(true)
  }

  // 🆕 处理编辑完成
  const handleEditCompleted = async () => {
    setShowSetupForm(false)
    setEditingPlan(null)
    setEditingBookTitle('')
    setShowCreateDialog(false)

    // 重新加载计划列表
    await loadPlans()

    toast.success('学习计划已更新')
  }

  // 检查是否可以创建新计划（最多3个）
  const canCreateMore = plans.length < 3

  // 获取当前选中的计划
  const selectedPlan = plans[selectedPlanIndex]

  // 获取计划对应的书籍信息
  const selectedBook = selectedPlan ? books.find(b => b.id === selectedPlan.book_id) : null

  // 🆕 骨架屏：先展示框架，数据加载中用骨架屏替代
  if (isLoading) {
    return (
      <>
        {/* 外层标题：今日学习计划 + 绿色方块 */}
        <div className="flex items-center gap-3 mb-4">
          <div className="w-4 h-8 bg-[#B4F416] border-2 border-black dark:border-slate-600 shadow-[2px_2px_0px_0px_#000] dark:shadow-none"></div>
          <h2 className="text-xl font-black text-black dark:text-slate-100 tracking-tighter uppercase italic">
            今日学习计划
          </h2>
        </div>

        {/* 🌟 外层大容器 - 骨架屏 */}
        <div className={`
          border-[3px] transition-colors duration-200 overflow-hidden
          ${isDark
            ? 'bg-[#1e293b] border-slate-700 shadow-none'
            : 'bg-white border-black shadow-[8px_8px_0px_0px_#000]'
          }
        `} style={{ height: '368px', backgroundColor: isDark ? '#1e293b' : 'white' }}>
          {/* PLAN_OS Header 骨架 */}
          <div className={`
            flex items-center justify-between px-3 py-1.5 border-b-[3px]
            ${isDark ? 'border-slate-700' : 'border-black'}
          `}>
            <div>
              <div className="h-4 w-16 bg-gray-200 dark:bg-slate-700 animate-pulse rounded mb-1"></div>
              <div className="h-2 w-24 bg-gray-200 dark:bg-slate-700 animate-pulse rounded"></div>
            </div>
            <div className="h-3.5 w-16 bg-gray-200 dark:bg-slate-700 animate-pulse rounded"></div>
          </div>

          {/* Tab 切换骨架 */}
          <div className="p-3 pt-3">
            <div className="flex justify-between items-end mb-[-3px]">
              {[1, 2].map((i) => (
                <div key={i} className="flex-1 mr-[-3px]">
                  <div className="h-12 bg-gray-200 dark:bg-slate-800 animate-pulse rounded"></div>
                </div>
              ))}
            </div>

            {/* 内容区域骨架 */}
            <div className={`mt-4 p-5 border-[3px] border-gray-200 dark:border-slate-700 rounded ${isDark ? 'bg-slate-800/50' : 'bg-gray-50'}`}>
              <div className="flex items-center justify-between mb-6">
                <div className="h-5 w-20 bg-gray-200 dark:bg-slate-700 animate-pulse rounded"></div>
                <div className="h-5 w-16 bg-gray-200 dark:bg-slate-700 animate-pulse rounded"></div>
              </div>

              {/* 数据展示骨架 */}
              <div className="grid grid-cols-2 gap-4 py-2">
                {[1, 2].map((i) => (
                  <div key={i} className="text-center">
                    <div className="h-16 w-16 mx-auto bg-gray-200 dark:bg-slate-700 animate-pulse rounded mb-2"></div>
                    <div className="h-3 w-12 mx-auto bg-gray-200 dark:bg-slate-700 animate-pulse rounded"></div>
                  </div>
                ))}
              </div>

              {/* 进度条骨架 */}
              <div className="pt-1 mt-4">
                <div className="h-3 w-full bg-gray-200 dark:bg-slate-700 animate-pulse rounded"></div>
              </div>
            </div>
          </div>
        </div>
      </>
    )
  }

  // 没有学习计划时
  if (plans.length === 0) {
    return (
      <>
        {/* 外层标题：今日学习计划 + 绿色方块 */}
        <div className="flex items-center gap-3 mb-4">
          <div className="w-4 h-8 bg-[#B4F416] border-2 border-black dark:border-slate-600 shadow-[2px_2px_0px_0px_#000] dark:shadow-none"></div>
          <h2 className="text-xl font-black text-black dark:text-slate-100 tracking-tighter uppercase italic">
            今日学习计划
          </h2>
        </div>

        {/* 空状态容器 */}
        <div className="p-6 md:p-8 border-[3px] border-black dark:border-white rounded shadow-[8px_8px_0px_0px_#000] bg-white dark:bg-[#1a1a1a]" style={{ height: '368px' }}>
          <div className="text-center space-y-6">
            <div className="w-20 h-20 mx-auto border-[3px] border-black dark:border-white rounded flex items-center justify-center bg-[#B4F416] shadow-[4px_4px_0px_0px_#000]">
              <Calendar className="w-10 h-10 text-black dark:text-black" strokeWidth={3} />
            </div>

            <div>
              <h2 className="text-xl md:text-2xl font-black mb-2 text-black dark:text-white uppercase italic">
                NO PLANS YET
              </h2>
              <p className="text-sm md:text-base font-bold text-gray-600 dark:text-gray-400 uppercase tracking-wider">
                创建你的第一个学习计划，开始科学的学习之旅！
              </p>
            </div>

            <button
              onClick={handleOpenCreateDialog}
              className="w-full px-8 py-4 text-base md:text-lg font-black text-black dark:text-white border-[3px] border-black dark:border-white bg-[#B4F416] rounded shadow-[6px_6px_0px_0px_#000] hover:translate-x-[2px] hover:translate-y-[2px] active:translate-x-[6px] active:translate-y-[6px] active:shadow-none transition-all duration-200 flex items-center gap-3 justify-center uppercase"
            >
              <Sparkles className="w-5 h-5" strokeWidth={3} />
              <span>创建学习计划</span>
            </button>
          </div>
        </div>

        {/* 创建对话框 */}
        <CreatePlanDialog />
      </>
    )
  }

  // 有学习计划时，显示Tab切换
  return (
    <>
      {/* 外层标题：今日学习计划 + 绿色方块 */}
      <div className="flex items-center gap-3 mb-4">
        <div className="w-4 h-8 bg-[#B4F416] border-2 border-black dark:border-slate-600 shadow-[2px_2px_0px_0px_#000] dark:shadow-none"></div>
        <h2 className="text-xl font-black text-black dark:text-slate-100 tracking-tighter uppercase italic">
          今日学习计划
        </h2>
      </div>

      {/* 🌟 外层大容器：PLAN_OS Header + 内容 */}
      <div
        className={`
          border-[3px] transition-colors duration-200 overflow-hidden
          ${isDark
            ? 'bg-[#1e293b] border-slate-700 shadow-none'
            : 'bg-white border-black shadow-[8px_8px_0px_0px_#000]'
          }
        `}
        style={{ height: '368px' }}
      >
        {/* 1. 顶部 Header (PLAN_OS) - 保持直角风格 */}
        <div className={`
          flex items-center justify-between px-3 py-1.5 border-b-[3px]
          ${isDark ? 'border-slate-700' : 'border-black'}
        `}>
          <div>
            <h2 className="text-base font-black italic tracking-tighter text-black dark:text-slate-100">
              PLAN_OS
            </h2>
            <p className="text-[7px] font-bold text-gray-400 dark:text-slate-500 tracking-widest uppercase">
              ACTIVE PLANS: {plans.length}/3
            </p>
          </div>
          {/* 日期移到右上角，颜色加深 */}
          <div className="font-mono text-[10px] font-black text-gray-600 dark:text-slate-400">
            {new Date().toLocaleDateString('zh-CN', {
              month: 'long',
              day: 'numeric'
            })}
          </div>
        </div>

        {/* 2. 主体区域 */}
        <div className="p-2.5 pt-2">

          {/* 🌟 标签 Tab (纯直角矩形) */}
          <div className="flex justify-between items-end mb-[-3px] relative z-10">
            {/* 标签区域 */}
            <div className="flex items-end gap-1 flex-1">
              {plans.map((plan, index) => {
                const book = books.find(b => b.id === plan.book_id)
                const isActive = index === selectedPlanIndex

                return (
                  <div
                    key={plan.id}
                    onClick={() => setSelectedPlanIndex(index)}
                    className={`
                      relative group cursor-pointer inline-flex items-center px-4 py-1.5 border-[3px] border-b-0 transition-all duration-200
                      ${isActive
                        ? isDark
                          ? 'bg-[#B4F416] border-slate-700 text-black'
                          : 'bg-[#B4F416] border-black text-black'
                        : isDark
                          ? 'bg-[#0f172a] border-slate-700 text-slate-500 hover:text-slate-300'
                          : 'bg-gray-100 border-black text-gray-500 hover:text-gray-700'
                      }
                    `}
                  >
                    <span className="text-xs font-black tracking-wide">
                      {book?.title || 'UNKNOWN'}
                    </span>
                  </div>
                )
              })}
            </div>

            {/* 右侧按钮区域 */}
            <div className="flex items-center gap-2 ml-2">
              {/* 新建学习计划按钮（当未满3个时显示） */}
              {canCreateMore && (
                <button
                  onClick={handleOpenCreateDialog}
                  className="
                    mb-0 px-1 py-0.5 text-[8px] font-black uppercase tracking-wider
                    border-[2px] border-black dark:border-slate-600
                    bg-[#B4F416] dark:bg-[#86efac]
                    text-black dark:text-black
                    shadow-[1px_1px_0px_0px_#000] dark:shadow-none
                    hover:translate-x-[0.5px] hover:translate-y-[0.5px]
                    hover:shadow-[0.5px_0.5px_0px_0px_#000]
                    active:translate-x-[1px] active:translate-y-[1px] active:shadow-none
                    transition-all duration-200
                    flex items-center gap-0.5
                  "
                >
                  <Plus className="w-1.5 h-1.5" strokeWidth={3} />
                  <span>新建</span>
                </button>
              )}
            </div>
          </div>

          {/* 🌟 当前计划的今日任务容器 */}
          {selectedPlan && selectedBook && (
            <DailyTaskDisplay
              key={selectedPlan.id}
              planId={selectedPlan.id}
              bookId={selectedPlan.book_id}
              plan={selectedPlan}
              bookTitle={selectedBook.title}
              onDeletePlan={handleDeletePlan}
              onEditPlan={handleEditPlan}
            />
          )}
        </div>
      </div>

      {/* 创建对话框 */}
      <CreatePlanDialog />
    </>
  )

  // 创建计划对话框组件
  function CreatePlanDialog() {
    if (!showCreateDialog) return null

    return (
      <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-end sm:items-center justify-center z-50 p-0 sm:p-4">
        {/* 移动端：从底部弹出的全屏卡片；PC端：居中弹窗 */}
        <div className={`w-full sm:max-w-md ${
          isDark ? 'bg-[#0f172a]' : 'bg-white'
        } border-[3px] border-black dark:border-slate-600 shadow-[8px_8px_0px_0px_#000] dark:shadow-none h-auto max-h-[95vh] sm:max-h-[85vh] overflow-hidden flex flex-col rounded-t sm:rounded border-b-0 sm:border-b-[3px]`}>
          {/* Header - Neo-Brutalism */}
          <div className="flex-shrink-0 flex items-center justify-between px-4 py-3 border-b-[3px] border-black dark:border-slate-600 bg-[#B4F416]">
            <h2 className="text-base sm:text-lg font-black uppercase tracking-tight text-black">
              {editingPlan ? '修改' : '创建'}学习计划
            </h2>
            <button
              onClick={() => {
                setShowCreateDialog(false)
                setShowSetupForm(false)
                setSelectedBookForPlan(null)
                setEditingPlan(null)
                setEditingBookTitle('')
              }}
              className="p-1.5 border-2 border-black dark:border-slate-700 bg-white dark:bg-[#0f172a] shadow-[2px_2px_0px_0px_#000] dark:shadow-none hover:translate-x-[1px] hover:translate-y-[1px] active:translate-x-[2px] active:translate-y-[2px] active:shadow-none transition-all"
            >
              <X className="w-4 h-4 text-black dark:text-white" strokeWidth={3} />
            </button>
          </div>

          {/* Content - 可滚动区域 */}
          <div className="flex-1 overflow-y-auto p-4 space-y-4 min-h-0">
            {!showSetupForm && (
              <>
                <p className={`text-xs font-black uppercase tracking-wider ${
                  isDark ? 'text-slate-500' : 'text-gray-600'
                }`}>
                  选择一个单词书开始你的学习之旅
                </p>

                {/* 书籍列表 */}
                <div className="space-y-3">
                  {books.map((book) => {
                    const hasPlan = plans.some(p => p.book_id === book.id)

                    return (
                      <div
                        key={book.id}
                        onClick={() => !hasPlan && handleSelectBookForPlan(book)}
                        className={`p-4 border-2 border-black dark:border-slate-600 cursor-pointer transition-all ${
                          isDark ? 'bg-[#1e293b]' : 'bg-white'
                        } shadow-[2px_2px_0px_0px_rgba(0,0,0,0.5)] dark:shadow-none ${
                          hasPlan
                            ? 'opacity-50 cursor-not-allowed'
                            : 'hover:shadow-[4px_4px_0px_0px_rgba(0,0,0,0.8)] hover:-translate-x-[1px] hover:-translate-y-[1px] active:shadow-none active:translate-x-[2px] active:translate-y-[2px]'
                        }`}
                      >
                        <div className="flex items-start gap-3">
                          <div className="w-10 h-10 border-2 border-black dark:border-slate-600 flex items-center justify-center shrink-0 bg-[#B4F416]">
                            <BookOpen className="w-5 h-5 text-black" strokeWidth={2.5} />
                          </div>
                          <div className="flex-1 min-w-0">
                            <h3 className={`text-sm font-black mb-1 truncate ${
                              isDark ? 'text-white' : 'text-black'
                            }`}>
                              {book.title}
                            </h3>
                            {book.description && (
                              <p className={`text-[10px] mb-2 line-clamp-2 font-bold ${
                                isDark ? 'text-slate-500' : 'text-gray-600'
                              }`}>
                                {book.description}
                              </p>
                            )}
                            <div className="text-[10px] font-mono font-bold text-[#B4F416]">
                              {book.total_words?.toLocaleString() || 0} 词
                            </div>
                          </div>
                        </div>

                        {hasPlan && (
                          <div className="mt-3 text-[10px] font-black uppercase px-2 py-1 text-center border-2 border-black dark:border-slate-600 bg-yellow-300 dark:bg-yellow-600 text-black dark:text-white">
                            已有计划
                          </div>
                        )}
                      </div>
                    )
                  })}
                </div>

                {books.length === 0 && (
                  <div className="text-center py-12">
                    <BookOpen className={`w-16 h-16 mx-auto mb-4 ${isDark ? 'text-slate-700' : 'text-gray-300'}`} />
                    <p className={`text-sm font-bold ${isDark ? 'text-slate-600' : 'text-gray-600'}`}>
                      暂无可用单词书
                    </p>
                  </div>
                )}
              </>
            )}

            {showSetupForm && (selectedBookForPlan || editingPlan) && (
              <LearningPlanSetup
                bookId={selectedBookForPlan?.id || editingPlan?.book_id || ''}
                bookTitle={selectedBookForPlan?.title || editingBookTitle}
                totalWords={selectedBookForPlan?.total_words || editingPlan?.total_words}
                editingPlan={editingPlan}
                onSuccess={editingPlan ? handleEditCompleted : handlePlanCreated}
                isInDialog={true}
                onCancel={() => {
                  setShowSetupForm(false)
                  setSelectedBookForPlan(null)
                  setEditingPlan(null)
                  setEditingBookTitle('')
                }}
              />
            )}
          </div>
        </div>
      </div>
    )
  }
}
